// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package evercoresqlite

import (
	"database/sql"
	"time"
)

type Aggregate struct {
	ID              int64
	AggregateTypeID int64
	NaturalKey      sql.NullString
}

type AggregateType struct {
	ID   int64
	Name string
}

type Event struct {
	ID          int64
	AggregateID int64
	Sequence    int64
	EventTypeID int64
	State       string
	EventTime   time.Time
	Reference   string
}

type EventLog struct {
	ID              int64
	AggregateID     int64
	NaturalKey      sql.NullString
	Sequence        int64
	AggregateTypeID int64
	AggregateType   string
	EventTypeID     int64
	EventType       string
	EventTime       time.Time
	State           string
}

type EventType struct {
	ID   int64
	Name string
}

type Snapshot struct {
	ID          int64
	AggregateID int64
	Sequence    int64
	State       string
}

type Subscription struct {
	ID              int64
	Name            string
	AggregateTypeID sql.NullInt64
	EventTypeID     sql.NullInt64
	AggregateKey    sql.NullString
	StartFrom       string
	StartEventID    int64
	StartTimestamp  sql.NullTime
	LastEventID     int64
	Active          bool
	LeaseOwner      sql.NullString
	LeaseExpiresAt  sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type SubscriptionEventType struct {
	SubscriptionID int64
	EventTypeID    int64
}
